In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
# 1D Array

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [4]:
print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [9]:
# Vector addition
v3_add = v1 + v2 #count value based on index
print(v3_add)

[5 7 9]


In [10]:
# Vector dot product
dot_product = np.dot(v1,v2) #multiply value based on index then count
print(dot_product)

32


In [13]:
# Vector norm(magnitude)
norm_v1 = np.linalg.norm(v1)
print(norm_v1)
# working like v1 -> 1 sqare ,2 s..,3...

3.7416573867739413


In [15]:
# Matrix
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [16]:
 # Matrix Addition
matrix_addition = A+B
print(matrix_addition)

[[ 6  8]
 [10 12]]


In [19]:
# Matrix multiplication (element wise and dot product)
element_wise_mul = A*B
dot_product_matrix = np.dot(A,B) # A in row direction & B in column direction

print(A)
print(B)
print(element_wise_mul)
print(dot_product_matrix)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [20]:
L = np.random.rand(3,2)
M = np.random.rand(2,4)
P = np.dot(L,M)
print(L)
print(M)
print(P)


[[0.3673872  0.38885853]
 [0.0832016  0.08668499]
 [0.16451954 0.91530333]]
[[0.12916412 0.63960353 0.29179918 0.20389606]
 [0.94579407 0.22053921 0.71208667 0.82006536]]
[[0.41523334 0.3207407  0.38410426 0.39379821]
 [0.09273281 0.07233348 0.08600539 0.08805184]
 [0.88693848 0.30708756 0.69978196 0.78415344]]


In [21]:
# Matrix Transpose(Flip)
transpose_A = A.T
print(A)
print(transpose_A)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [22]:
# Determinanents
det_A = np.linalg.det(A)
print(det_A)

-2.0000000000000004
